apiVersion: v1
kind: ConfigMap
metadata:
  name: stayflow-config
  namespace: stayflow-staging
data:
  DB_TEST_URL: jdbc:postgresql://postgres:5432/stayflow_test
  MAIL_HOST: smtp.gmail.com
  APP_COMMISSION_RATE: "0.10"
  NEXT_PUBLIC_API_URL: http://localhost:8080
