apiVersion: v1
kind: Secret
metadata:
  name: stayflow-secret
  namespace: stayflow-staging
type: Opaque
stringData:
  DB_USER: CHANGE_ME
  DB_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME
  ADMIN_EMAIL: CHANGE_ME
  ADMIN_PASSWORD: CHANGE_ME
  MAIL_USERNAME: CHANGE_ME
  MAIL_PASSWORD: CHANGE_ME
  CLOUD_NAME: CHANGE_ME
  CLOUD_API_KEY: CHANGE_ME
  CLOUD_API_SECRET: CHANGE_ME
