apiVersion: v1
kind: ConfigMap
metadata:
  name: stayflow-config
  namespace: stayflow-staging
data:
  MAIL_HOST: smtp.gmail.com
  APP_COMMISSION_RATE: "0.10"
  SPRING_PROFILES_ACTIVE: staging
  NEXT_PUBLIC_API_URL: http://stayflow-staging.local
